# fly.toml app configuration file generated for harmony-llm-chromadb on 2023-10-13T12:25:38-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "harmony-llm-chromadb"
primary_region = "den"

[build]

[[mounts]]
  source = "llm_api_chromadb"
  destination = "/data"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
